### PR TITLE
Peter's edits

### PR DESCRIPTION
**Pull request by PeterBell**
Hey @1point618 , this is a PR for my edits to the add-outline branch so we can comment on them. Please don't merge it yet - only reviewed and tweaked the first file. I'll ping you once it's ready for your review. If you review, make any changes you want on this branch, @ mention me when we're good to go and I'll merge this into your branch and close the PR.

### CODE REVIEW

**Comment by 1point618** [comment]
OK sounds good!

**Comment by PeterBell** [comment]
Hey @1point618 I removed the markup for what to be video vs screencast - I think I have a better idea. It's a little more work for us both, but I think it'd be worth it. How about I shoot _everything_ as head and shoulders video. Then you can use screenflow pro (I'll run you through it) to take whatever subset of that you want, replace video with screen capture where it makes sense, and of course you can just throw away anything I record that feels like it'd be better just as text. That way we shoot once and if we want to later decide a different editing choice it's just a matter of going back to the source materials as we'll have both video and audio for everything.

Thoughts?

**Comment by PeterBell** [comment]
Quick note that 04-templates.md doesn't appear to be completed, so edited what we have so far, but it's still not ready to shoot.

**Comment by PeterBell** [comment]
Again, the install jeckyll page doesn't appear to be complete but I've edited what's there

**Comment by PeterBell** [comment]
OK @1point618 I think these changes are good for your :eyes:

**Comment by 1point618** [comment]
@PeterBell 

04 and 05 still need to get finished up. Any edits now are really helpful though.

Shooting everything as video could work, but there is still some placeholder text in there waiting on the project to be completed. When would you want to shoot the whole thing? Because I need to have the text 100% locked in by then.

I think I'm leaning towards shooting at least the text that we know we want as video first...

**Comment by 1point618** [comment]
@PeterBell All of these edits look good so I'm going to merge it in.

**Comment by PeterBell** [comment]
@1point618 I edited everything there was, probably best to review and merge this in and I can create another "edit" PR once copy is closer to done.

I suggest we just shoot everything we have - easier to throw away a paragraph than to have to re-record if it doesn't work as text for some reason. Going to try to get some time on video today or worst case tomorrow so can shoot this Friday or Monday depending on your timing.

LMK when we're good to merge (or any comments if we're not!)

**Comment by 1point618** [comment]
Ah dueling comments. Just merged this.

If you think that's going to be easier for recording, then let's do it. Lesson 1 is 100% and 2 and 3 are 95% completed, so we can start with those.

**Pull request merged**
